### ISSUE TITLE
Dataset Missingness Classification MNAR, MAR & MCAR ? 

### ISSUE THREAD

**Issue by Elixirman** [JeevalShah/ElectricityAccessVisualizationProject#1]
[Missing Data Classification Report.docx](https://github.com/JeevalShah/ElectricityAccessVisualizationProject/files/15255998/Missing.Data.Classification.Report.docx)

I believe this review is critically crucial to our work and we need to conclude as the clock is ticking away.

**Comment by JeevalShah** [comment]
> [Missing Data Classification Report.docx](https://github.com/JeevalShah/ElectricityAccessVisualizationProject/files/15255998/Missing.Data.Classification.Report.docx)
> 
> I believe this review is critically crucial to our work and we need to conclude as the clock is ticking away.

For the most part, your review is detailed with proper evidentiary backing. However, I noticed a couple of issues & have fixed them. I am attaching the modified report here. If you are satisfied with the changes, then you can create a pull request.
[Missing Data Classification Report.docx](https://github.com/JeevalShah/ElectricityAccessVisualizationProject/files/15256959/Missing.Data.Classification.Report.docx)
[Missing Data Classification Report.pdf](https://github.com/JeevalShah/ElectricityAccessVisualizationProject/files/15256961/Missing.Data.Classification.Report.pdf)
