### ISSUE TITLE
Dataset Fusion ( Lasso-Ridge-Linear) = Predicted_data

### ISSUE THREAD

**Issue by Elixirman** [JeevalShah/ElectricityAccessVisualizationProject#2]
[predicted_dataset_mean_lasso_ridge_linear.csv](https://github.com/JeevalShah/ElectricityAccessVisualizationProject/files/15322783/predicted_dataset_mean_lasso_ridge_linear.csv)

This is a suggestion to fusing all 3 datasets as one.

**Comment by Elixirman** [comment]
[Lasso_Ridge_Linear_Mean_Fusion.zip](https://github.com/JeevalShah/ElectricityAccessVisualizationProject/files/15322977/Lasso_Ridge_Linear_Mean_Fusion.zip)

This is the tag along colab note.

**Comment by JeevalShah** [comment]
I have added the csv files. Will look into adding the notebook.
